# Generated by Django 5.2 on 2025-06-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.TextField(max_length=100, verbose_name='Sobrenome')),
                ('endereco', models.TextField(max_length=100, verbose_name='endereço')),
                ('cpf', models.TextField(max_length=100, verbose_name='cpf')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
