# Generated by Django 5.2 on 2025-06-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=150, verbose_name='Primeiro-Nome')),
                ('segundo_nome', models.CharField(max_length=150, verbose_name='Segundo-Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereco')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Genenro')),
            ],
            options={
                'verbose_name': 'Item Adicional Pago',
                'verbose_name_plural': 'Itens Adicionais Pagos',
                'ordering': ['id'],
            },
        ),
    ]
