# Generated by Django 5.2 on 2025-06-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['id'], 'verbose_name': 'HomePage', 'verbose_name_plural': 'HomePages'},
        ),
    ]
